# Basic settings
title: Muhammad Afsah Mumtaz
description: CST1340 Blog
baseurl: "/ClassBlog"
url: ""

# Basic Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
show_excerpts: true
