# Basic settings
title: CST1340 Blog
author: Muhammad Afsah Mumtaz
baseurl: "/ClassBlog"
url: "https://NAME0x0.github.io"

# Build settings
markdown: GFM
highlighter: rouge
permalink: /:title/

exclude: [".git", ".gitignore", "README.md"]

# Plugins
plugins:
  - jekyll-default-layout
  - jekyll-titles-from-headers

# Sass
sass:
  style: compressed

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
